import './globals.css'
import type { Metadata } from 'next'
import { Barlow } from 'next/font/google'
import { Fraunces } from 'next/font/google'

const barlow = Barlow({weight: "600", subsets: ['latin'] })
const fraunces = Fraunces({ weight: "700", subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={barlow.className}>{children}</body>
    </html>
  )
}
