import "./globals.css";
import type { Metadata } from "next";
import { Barlow, Fraunces } from "next/font/google";
import Link from "next/link";
import Logo from "@/components/Logo";

const barlow = Barlow({ weight: "600", subsets: ["latin"] });
const fraunces = Fraunces({
  weight: ["700", "900"],
  subsets: ["latin"],
  variable: "--font-fraunces",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${barlow.className} ${fraunces.variable} text-lg`}>
        <header className="absolute left-0 right-0 top-0 z-50 flex items-center justify-between gap-4 p-4 text-white">
          <div>
            <Logo />
          </div>

          <nav>
            <ul className="flex items-center gap-4">
              <li>
                <Link href="#about">About</Link>
              </li>
              <li>
                <Link href="#services">Services</Link>
              </li>
              <li>
                <Link href="#projects">Projects</Link>
              </li>
            </ul>
          </nav>
        </header>

        {children}
      </body>
    </html>
  );
}
